"""Catalogo de ejercicios de la hoja "EJERCICIOS" (SANTA PERPETUA GYM),
clasificados por patron de movimiento dominante.

Esta clasificacion es solo para poder ofrecer un ejercicio de reemplazo del
mismo patron cuando una categoria tiene muy poco historial propio. La logica
principal de la propuesta (ver engine.py) reutiliza las parejas de ejercicios
que Juan/Nico ya programaron, no inventa combinaciones nuevas.
"""
from __future__ import annotations

PATTERN_SENTADILLA = "sentadilla"
PATTERN_UNILATERAL = "unilateral_pierna"
PATTERN_BISAGRA = "bisagra_cadera"
PATTERN_EMPUJE_H = "empuje_horizontal"
PATTERN_EMPUJE_V = "empuje_vertical"
PATTERN_TRACCION_H = "traccion_horizontal"
PATTERN_TRACCION_V = "traccion_vertical"
PATTERN_CORE_FLEXION = "core_flexion"
PATTERN_CORE_ROTACION = "core_rotacion"
PATTERN_CORE_ISOMETRICO = "core_isometrico"
PATTERN_PLIOMETRIA = "pliometria"
PATTERN_EXCENTRICO = "excentrico"
PATTERN_ACCESORIO = "accesorio_pie_tobillo"
PATTERN_VELOCIDAD = "velocidad_aceleracion"
PATTERN_AGILIDAD = "agilidad_coordinacion"
PATTERN_OLIMPICO = "olimpico_derivado"
PATTERN_POTENCIA = "lanzamientos_potencia"

EXERCISE_PATTERNS: dict[str, str] = {
    "SENTADILLA GLOBET": PATTERN_SENTADILLA,
    "SENTADILLA UNIPODAL": PATTERN_SENTADILLA,
    "SENTADILLA BÚLGARA": PATTERN_SENTADILLA,
    "SENTADILLA FRONTAL": PATTERN_SENTADILLA,
    "SENTADILLA TRASERA": PATTERN_SENTADILLA,
    "SENTADILLA ISOMÉTRICA": PATTERN_SENTADILLA,
    "SENTADILLA C/SALTO": PATTERN_SENTADILLA,
    "SENTADILLA SUMO": PATTERN_SENTADILLA,
    "ESTOCADA ATRAS": PATTERN_UNILATERAL,
    "ESTOCADA FRONTAL": PATTERN_UNILATERAL,
    "ESTOCADA COMPUESTA": PATTERN_UNILATERAL,
    "ESTOCADA DISOCIADA C/SALTO": PATTERN_UNILATERAL,
    "ALCANCE LATERAL": PATTERN_UNILATERAL,
    "SUBIDAS AL CAJÓN": PATTERN_UNILATERAL,
    "CAMINATA LATERAL GLUTEO MEDIO": PATTERN_UNILATERAL,
    "COPENAGHE": PATTERN_UNILATERAL,
    "PESO MUERTO A 1PP": PATTERN_BISAGRA,
    "PESO MUERTO RUMANO": PATTERN_BISAGRA,
    "PESO MUERTO ASIMETRICO": PATTERN_BISAGRA,
    "PESO MUERTO UNIPODAL": PATTERN_BISAGRA,
    "PESO MUERTO CONVENCIONAL": PATTERN_BISAGRA,
    "PESO MUERTO C/DISCO": PATTERN_BISAGRA,
    "PESO MUERTO C/CORE BAG": PATTERN_BISAGRA,
    "PESO MUERTO C/MANCUERNA": PATTERN_BISAGRA,
    "PUENTE DE GLÚTEO C/CORE BAG": PATTERN_BISAGRA,
    "PUENTE DE GLUTEO C/DISCO": PATTERN_BISAGRA,
    "PUENTE DE GLUTEO A 1PP C/DISCO": PATTERN_BISAGRA,
    "PUENTE DE GLUTEO A 1PP C/CORE BAG": PATTERN_BISAGRA,
    "PUENTE DE GLÚTEO + PRESS": PATTERN_BISAGRA,
    "HIP THRUST": PATTERN_BISAGRA,
    "PUENTE DE GLUTEO C/FITBALL": PATTERN_BISAGRA,
    "FLEXIONES CON DISCO": PATTERN_EMPUJE_H,
    "FLEXIONES CON AGARRE X": PATTERN_EMPUJE_H,
    "PRESS BANCO": PATTERN_EMPUJE_H,
    "PRESS C/ELÁSTICO": PATTERN_EMPUJE_H,
    "PRESS EN TRX": PATTERN_EMPUJE_H,
    "PRESS ARNOLD": PATTERN_EMPUJE_V,
    "PRESS ARNOLD C/DISCO": PATTERN_EMPUJE_V,
    "PRESS MILITAR": PATTERN_EMPUJE_V,
    "PRESS A 1BB": PATTERN_EMPUJE_V,
    "REMO C/ELÁSTICO": PATTERN_TRACCION_H,
    "REMO GORILLA": PATTERN_TRACCION_H,
    "REMO EN PLANCHA ALTA": PATTERN_TRACCION_H,
    "REMO A 90 C/BARRA": PATTERN_TRACCION_H,
    "REMO A 45 C/BARRA": PATTERN_TRACCION_H,
    "REMO A 1BB": PATTERN_TRACCION_H,
    "REMO INVERTIDO": PATTERN_TRACCION_H,
    "REMO EN TRX": PATTERN_TRACCION_H,
    "REMO AL MENTON CON BARRA": PATTERN_TRACCION_H,
    "REMO C/CORE BAG": PATTERN_TRACCION_H,
    "REMO CON DISCOS": PATTERN_TRACCION_H,
    "DOMINADAS": PATTERN_TRACCION_V,
    "DOMINADAS C/BANDA": PATTERN_TRACCION_V,
    "ESPINALES NADO": PATTERN_CORE_FLEXION,
    "ESPINALES DISOCIADAS": PATTERN_CORE_FLEXION,
    "ABDOMINALES TOCÓ TALONES": PATTERN_CORE_FLEXION,
    "ABDOMINALES SUPERIORES": PATTERN_CORE_FLEXION,
    "ABDOMINALES CORTITOS": PATTERN_CORE_FLEXION,
    "TWIST RUSO": PATTERN_CORE_ROTACION,
    "ANTIROTACION C/ELASTICO": PATTERN_CORE_ROTACION,
    "DEAD BUG": PATTERN_CORE_ISOMETRICO,
    "ANTI EXTENSIÓN C/ELASTICO": PATTERN_CORE_ISOMETRICO,
    "ANTI FLEXIÓN": PATTERN_CORE_ISOMETRICO,
    "PRESS PALLOF": PATTERN_CORE_ISOMETRICO,
    "PLANCHA ALTA EN CAJÓN C/FITBALL": PATTERN_CORE_ISOMETRICO,
    "PLANCHA ALTA": PATTERN_CORE_ISOMETRICO,
    "PLANCHA LATERAL": PATTERN_CORE_ISOMETRICO,
    "PLANCHA DE CODOS": PATTERN_CORE_ISOMETRICO,
    "SALTABILIDAD VERTICAL": PATTERN_PLIOMETRIA,
    "SALTABILIDAD HORIZONTAL": PATTERN_PLIOMETRIA,
    "SALTOS AL CAJÓN": PATTERN_PLIOMETRIA,
    "SALTABILIDAD LATERAL": PATTERN_PLIOMETRIA,
    "SALTOS COMBINADOS": PATTERN_PLIOMETRIA,
    "SALTOS ASISTIDOS C/ELÁSTICO": PATTERN_PLIOMETRIA,
    "CAIDAS DEL CAJÓN": PATTERN_PLIOMETRIA,
    "EXCENTRICO DE ISQUIOS ARRODILLADO": PATTERN_EXCENTRICO,
    "EXCENTRICO DE ISQUIOS C/FITBALL": PATTERN_EXCENTRICO,
    "EXCENTRICO DE CUADRICEPS ARRODILLADO": PATTERN_EXCENTRICO,
    "GEMELOS C/MANCUERNA": PATTERN_ACCESORIO,
    "GEMELOS A 1PP": PATTERN_ACCESORIO,
    "APRETAR PELOTA C/FITBALL": PATTERN_ACCESORIO,
    "ACELERACIONES C/BANDA": PATTERN_VELOCIDAD,
    "FRENADO C/BANDA": PATTERN_VELOCIDAD,
    "ACELERACIONES": PATTERN_VELOCIDAD,
    "DESACELERACIONES": PATTERN_VELOCIDAD,
    "SKIPPING C/BANDA": PATTERN_VELOCIDAD,
    "COORDINATIVO CON CHINOS": PATTERN_AGILIDAD,
    "COORDINATIVO C/DISCO": PATTERN_AGILIDAD,
    "COORDINATIVO CON VALLA": PATTERN_AGILIDAD,
    "CÓNICAS SALIDA": PATTERN_AGILIDAD,
    "CÓNICAS FRENADO": PATTERN_AGILIDAD,
    "VITALIZACIONES C/D": PATTERN_AGILIDAD,
    "CARGADAS": PATTERN_OLIMPICO,
    "SEGUNDO TIEMPO": PATTERN_OLIMPICO,
    "MONIGOTE": PATTERN_OLIMPICO,
    "SNATCH": PATTERN_OLIMPICO,
    "ARRANQUE A 1BB": PATTERN_OLIMPICO,
    "DUELOS CON FITBALL": PATTERN_POTENCIA,
    "LANZAMIENTOS FRONTALES": PATTERN_POTENCIA,
    "LANZAMIENTOS ROTACIONALES": PATTERN_POTENCIA,
    "TRANSPORTES": PATTERN_POTENCIA,
}

# Entradas del catalogo que no son ejercicios reales (notas de asistencia, etc.)
NON_EXERCISE_ENTRIES = {"NO ASISTIÓ EL GRUPO"}


def normalize_name(name: str) -> str:
    return " ".join(name.strip().upper().split())


def pattern_of(exercise_name: str) -> str | None:
    return EXERCISE_PATTERNS.get(normalize_name(exercise_name))


def exercises_by_pattern(pattern: str) -> list[str]:
    return sorted(name for name, p in EXERCISE_PATTERNS.items() if p == pattern)


def is_known_exercise(name: str) -> bool:
    n = normalize_name(name)
    return n in EXERCISE_PATTERNS or n in NON_EXERCISE_ENTRIES


# Clasificacion troncal/auxiliar (para la super serie): troncal = ejercicio
# multiarticular con carga externa relevante; auxiliar = core, pliometria,
# velocidad/agilidad, excentricos y accesorios. Se usa para decidir cuanto
# sube cada uno en la progresion (+2 reps troncal, +1 auxiliar).
TRONCAL_PATTERNS = {
    PATTERN_SENTADILLA,
    PATTERN_UNILATERAL,
    PATTERN_BISAGRA,
    PATTERN_EMPUJE_H,
    PATTERN_EMPUJE_V,
    PATTERN_TRACCION_H,
    PATTERN_TRACCION_V,
    PATTERN_OLIMPICO,
}
AUXILIAR_PATTERNS = {
    PATTERN_CORE_FLEXION,
    PATTERN_CORE_ROTACION,
    PATTERN_CORE_ISOMETRICO,
    PATTERN_PLIOMETRIA,
    PATTERN_EXCENTRICO,
    PATTERN_ACCESORIO,
    PATTERN_VELOCIDAD,
    PATTERN_AGILIDAD,
    PATTERN_POTENCIA,
}

TRONCAL = "troncal"
AUXILIAR = "auxiliar"


def classify_troncal_auxiliar(exercise_name: str) -> str | None:
    pattern = pattern_of(exercise_name)
    if pattern in TRONCAL_PATTERNS:
        return TRONCAL
    if pattern in AUXILIAR_PATTERNS:
        return AUXILIAR
    return None
